<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE group [
		<!ELEMENT group (student*)>
		<!ELEMENT student (subject*,average?)>
		<!ATTLIST student
				firstname CDATA #REQUIRED
				lastname CDATA #REQUIRED
				groupnumber CDATA #REQUIRED >
		<!ELEMENT subject EMPTY>
		<!ATTLIST subject
				title CDATA #REQUIRED
				mark (1|2|3|4|5) #REQUIRED >
		<!ELEMENT average (#PCDATA)>
		]>
<group>
	<student firstname="Cot" lastname="Matroskin" groupnumber="10">
		<subject title="Art" mark="1"/>
		<subject title="Math" mark="1"/>
		<subject title="Programming" mark="1"/>
		<subject title="Biology" mark="1"/>
		<average>5</average>
	</student>
	<student firstname="Gena" lastname="Crocodil" groupnumber="10">
		<subject title="Art" mark="3"/>
		<subject title="Math" mark="5"/>
		<subject title="Programming" mark="4"/>
		<subject title="Biology" mark="5"/>
		<average>5</average>
	</student>
	<student firstname="Solovei" lastname="Razboinic" groupnumber="10">
		<subject title="Art" mark="4"/>
		<subject title="Math" mark="3"/>
		<subject title="Programming" mark="4"/>
		<subject title="Biology" mark="3"/>
		<average>5</average>
	</student>
</group>
